



specialty = [
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
      imgurl: "../image/food/food123.png",
      imgheight: "2.8",
      info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
    },
    {
      imgurl: "../image/food/egg123.png",
      imgheight: "3.6",
      info: "休闲蛋类特产5",
      moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
    },
    {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      {
        imgurl: "../image/food/food123.png",
        imgheight: "2.8",
        info: "休闲肉类特产5休休闲肉类特产55闲肉类闲肉类",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场",
      },
      {
        imgurl: "../image/food/egg123.png",
        imgheight: "3.6",
        info: "休闲蛋类特产5",
        moreinfo: "库存有限 卖完即止 超好吃 椒香麻爽 美味嗨翻整场库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止库存有限 卖完即止 超好吃 特制皮蛋 美味嗨翻整场库存有限 卖完即止",
      },
      
  ];



